# Site
name: "Outsourcery"
title: "Outsourcery"
description: "The Milk Men Guide for Business Owners to get the most from their IT."
logo: 'assets/images/logo.png'
favicon: 'assets/images/logo.png'
baseurl: /
google_analytics: ''
disqus: ''
mailchimp-list: ''
include: ["_pages"]
permalink: /:title/

# Authors
authors:
  james:
    name: James
    display_name: James
    avatar: '/assets/images/james.jpg'
    gravatar: 
    email: hello@themilkmen.com
    web: https://themilkmen.com
    twitter: https://twitter.com/themilkmen
    description: ""
  charles:
    name: Charles
    display_name: Charlies    
    avatar: ''
    gravatar: 
    email: hello@themilkmen.com
    web: https://themilkmen.com
    twitter: https://twitter.com/themilkmen
    description: ""

# Plugins
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-archives
    
# Archives
jekyll-archives:
  enabled:
    - categories
  layout: archive
  permalinks:
    category: '/category/:name/'
    
# Pagination 
paginate: 6
paginate_path: /page:num/
    
# Other
markdown: kramdown

kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: true

# Adsense (change to "enabled" to activate, also your client id and ad slot. Create a new ad unit from your Adsense account to get the slot.)
adsense: "disabled"
adsense-data-ad-client: "ca-pub-3412143450191416"
adsense-data-ad-slot: "1363087678"

# Lazy Images ("enabled" or "disabled")
lazyimages: "disabled"

exclude: [changelog.md, LICENSE.txt, README.md, Gemfile, Gemfile.lock]
